[window]
startup_mode = "Maximized"
decorations = "None"

[env]
term = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 12

[colors.primary]
background = "#1B1E26"
